"""SendySettings Dialog

This class implements the settings dialog for the Sendy Cropper application.
It provides a graphical interface to configure various application settings
such as photo processing parameters, image counter paths and exceptions,
image loader path, UI theme, and autorun behavior on Windows startup.

Key features:
- Load and save settings to the global `data` object.
- Set and apply QSS (Qt Style Sheets) for theming.
- Validate input fields and enable/disable the apply button.
- Add or remove the application from Windows autostart.

Methods:
- set_QSS(): Loads and applies the QSS stylesheet to the application.
- keyPressEvent(event): Handles Delete key for removing selected list items.
- closeEvent(event): Clears temporary UI elements on dialog close.
- fill_values(): Fills the UI widgets with current values from `data`.
- button_browse_pushed(lineedit): Opens a folder selection dialog and sets the result in a QLineEdit.
- image_counter_exceptions_add_item(): Adds a new exception to the exceptions list.
- exceptions_edit_item(item): Edits an existing exception by moving it to the input field.
- add_app_to_system_startup(): Adds or removes the app from Windows startup based on checkbox state.
- check_validation(): Validates all input fields and updates the apply button state.
- button_apply_settings_pushed(): Applies the current settings from the UI to `data` and saves them.

Attributes:
- ui: The UI object generated by Qt Designer.
- main_window: Reference to the main application window.
  """


import logging
from pathlib import Path
import sys
from functools import partial
import winreg
import os

from PyQt5.QtWidgets import QDialog, QFileDialog, QListWidgetItem
from PyQt5.QtWidgets import QApplication
from PyQt5.QtGui import QCloseEvent
from PyQt5.QtCore import Qt, QFile, QTextStream

from cropper.settings_ui import Ui_SendySettings
from data import data

logger = logging.getLogger(__name__)


class SendySettings(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)

        # Window configuration
        self.main_window = parent
        self.ui = Ui_SendySettings()
        self.ui.setupUi(self)

        # Button clicked
        self.ui.pushButton_set_photo_processing_path.clicked.connect(partial(
            self.button_browse_pushed,
            self.ui.lineEdit_photo_processing_path)
        )
        self.ui.pushButton_set_image_counter_path.clicked.connect(partial(
            self.button_browse_pushed,
            self.ui.lineEdit_image_counter_path)
        )
        self.ui.pushButton_set_image_loader_path.clicked.connect(partial(
            self.button_browse_pushed,
            self.ui.lineEdit_image_loader_path)
        )
        self.ui.pushButton_image_counter_exceptions_add_elem.clicked.connect(self.image_counter_exceptions_add_item)
        self.ui.pushButton_settings_apply.clicked.connect(self.button_apply_settings_pushed)
        self.ui.lineEdit_image_counter_exceptions_add_elem.returnPressed.connect(self.image_counter_exceptions_add_item)
        self.ui.checkBox.stateChanged.connect(self.add_app_to_system_startup)

        self.fill_values()

        widget_list = [self.ui.lineEdit_photo_processing_path,
                       self.ui.lineEdit_photo_processing_wrap,
                       self.ui.lineEdit_photo_processing_white,
                       self.ui.lineEdit_photo_processing_black,
                       self.ui.lineEdit_photo_processing_dpi,
                       self.ui.lineEdit_photo_processing_fontsize,
                       self.ui.lineEdit_photo_processing_crop,
                       self.ui.lineEdit_image_counter_path,
                       self.ui.lineEdit_image_loader_path
                       ]
        for widget in widget_list:
            widget.textChanged.connect(self.check_validation)

        # Variables
        self.error_qss = """
                                QLineEdit {
                                    border: 2px solid #FF6B6B;
                                    color: #fa5f5f;
                                }
    
                                QPushButton {
                                    border: 2px solid #fa5f5f;
                                    color: #fa5f5f;
                                    background-color: #424242;
                                }
    
                                QPushButton {
                                    border: 2px solid #fa5f5f;
                                    color: #fa5f5f;
                                    background-color: #424242;
                                }
                            """

    def set_QSS(self):
        try:
            qss_file = QFile(':/cropper_dark.css')
            if not qss_file.exists():
                logger.error('No QSS file in resources')
                return

            if qss_file.open(QFile.ReadOnly | QFile.Text):
                stream = QTextStream(qss_file)
                qss = stream.readAll()
                qss_file.close()
                logger.debug('QSS is loaded')
                QApplication.instance().setStyleSheet(qss)
            else:
                logger.error('Cannot open QSS file')
                return

        except Exception:
            logger.exception(f'Cannot load CSS')
            return

    def keyPressEvent(self, event):
        exceptions = self.ui.listWidget_image_counter_exceptions
        if event.key() == Qt.Key_Delete:
            if self.focusWidget() == exceptions:
                item = exceptions.currentItem()
                if item:
                    row = exceptions.row(item)
                    exceptions.takeItem(row)

    def closeEvent(self, event: QCloseEvent):
        self.ui.listWidget_image_counter_exceptions.clear()
        self.fill_values()
        super().closeEvent(event)

    def fill_values(self):
        # main
        current_theme = {':/cropper_bright.css': 0, ':/cropper_dark.css': 1}
        self.ui.comboBox_theme.setCurrentIndex(current_theme[data.cropper_css])

        # photo processing
        self.ui.lineEdit_photo_processing_path.setText(str(data.photo_processing_path))
        self.ui.lineEdit_photo_processing_wrap.setText(str(data.photo_processing_wrap_cm))
        self.ui.lineEdit_photo_processing_white.setText(str(data.photo_processing_white_cm))
        self.ui.lineEdit_photo_processing_black.setText(str(data.photo_processing_black_px))
        self.ui.lineEdit_photo_processing_dpi.setText(str(data.photo_processing_dpi))
        self.ui.lineEdit_photo_processing_fontsize.setText(str(data.photo_processing_font_size_px))
        self.ui.lineEdit_photo_processing_crop.setText(str(data.photo_processing_crop_px))

        # image counter
        self.ui.lineEdit_image_counter_path.setText(str(data.image_counter_path))
        self.ui.listWidget_image_counter_exceptions.addItems(data.image_counter_exceptions)
        self.ui.listWidget_image_counter_exceptions.itemDoubleClicked.connect(self.exceptions_edit_item)

        # image loader
        self.ui.lineEdit_image_loader_path.setText(str(data.image_loader_path))

        # autorun
        app_name = "SendyApp"
        key_path = r"Software\Microsoft\Windows\CurrentVersion\Run"

        try:
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, key_path, 0, winreg.KEY_READ) as reg_key:
                value, _ = winreg.QueryValueEx(reg_key, app_name)
                self.ui.checkBox.setChecked(True)
        except FileNotFoundError:
            self.ui.checkBox.setChecked(False)

    def button_browse_pushed(self, lineedit):
        folder = QFileDialog.getExistingDirectory(
            self,
            "Выберите папку",
            "",
            QFileDialog.ShowDirsOnly
        )
        if folder:
            lineedit.setText(folder)

    def image_counter_exceptions_add_item(self):
        text = self.ui.lineEdit_image_counter_exceptions_add_elem.text()
        item = QListWidgetItem(text)
        if text:
            self.ui.listWidget_image_counter_exceptions.addItem(item)
            self.ui.listWidget_image_counter_exceptions.scrollToItem(item)
            self.ui.listWidget_image_counter_exceptions.setCurrentItem(item)
            self.ui.lineEdit_image_counter_exceptions_add_elem.setText('')

    def exceptions_edit_item(self, item):
        self.ui.lineEdit_image_counter_exceptions_add_elem.setText(item.text())
        self.ui.listWidget_image_counter_exceptions.takeItem(
            self.ui.listWidget_image_counter_exceptions.row(item))

    def add_app_to_system_startup(self):
        directory = os.getcwd()
        application: str = "Sendy.exe"
        exe_path = os.path.join(directory, application)
        key_path = r"Software\Microsoft\Windows\CurrentVersion\Run"

        if self.ui.checkBox.isChecked():
            try:
                with winreg.OpenKey(winreg.HKEY_CURRENT_USER, key_path, 0, winreg.KEY_SET_VALUE) as reg_key:
                    winreg.SetValueEx(reg_key, "SendyApp", 0, winreg.REG_SZ, f'"{exe_path}"')
            except:
                logger.exception("Can't add Sendy to autorun")
            logger.info('Sendy app will start on system boot')

        else:
            try:
                with winreg.OpenKey(winreg.HKEY_CURRENT_USER, key_path, 0, winreg.KEY_SET_VALUE) as reg_key:
                    try:
                        winreg.DeleteValue(reg_key, "SendyApp")
                        logger.info('SendyApp removed from autostart')
                    except FileNotFoundError:
                        logger.info('SendyApp not found in autostart')
            except:
                logger.exception('Sendy deleting from autostart error')

    def check_validation(self):
        def invalid_data(widget):
            widget.setStyleSheet(self.error_qss)
            return False

        def valid_data(widget):
            widget.setStyleSheet('')
            return True

        def check_validation(widget, validator):
            try:
                if validator(widget):
                    return valid_data(widget)
                else:
                    return invalid_data(widget)
            except Exception as e:
                return invalid_data(widget)

        check_list = [
            # photo processing
            check_validation(self.ui.lineEdit_photo_processing_path, lambda p: Path(p.text()).exists()),
            check_validation(self.ui.lineEdit_photo_processing_wrap, lambda x: float(x.text()) >= 0),
            check_validation(self.ui.lineEdit_photo_processing_white, lambda x: float(x.text()) >= 0),
            check_validation(self.ui.lineEdit_photo_processing_black, lambda x: int(x.text()) >= 0),
            check_validation(self.ui.lineEdit_photo_processing_dpi, lambda x: 1 <= int(x.text()) <= 500),
            check_validation(self.ui.lineEdit_photo_processing_fontsize, lambda x: 1 <= int(x.text()) <= 500),
            check_validation(self.ui.lineEdit_photo_processing_crop, lambda x: 1 <= int(x.text()) <= 500),

            # image counter
            check_validation(self.ui.lineEdit_image_counter_path, lambda p: Path(p.text()).exists()),

            # image loader
            check_validation(self.ui.lineEdit_image_loader_path, lambda p: Path(p.text()).exists())
        ]

        all_valid = all(check_list)
        self.ui.pushButton_settings_apply.setEnabled(all_valid)
        self.ui.pushButton_settings_apply.setStyleSheet('' if all_valid else self.error_qss)

    def button_apply_settings_pushed(self):
        # main
        themes = {0: ':/cropper_bright.css', 1: ':/cropper_dark.css'}
        data.cropper_css = themes[self.ui.comboBox_theme.currentIndex()]
        self.main_window.set_QSS()

        # photo processing
        data.photo_processing_path = Path(self.ui.lineEdit_photo_processing_path.text())
        data.photo_processing_wrap_cm = float(self.ui.lineEdit_photo_processing_wrap.text())
        data.photo_processing_white_cm = float(self.ui.lineEdit_photo_processing_white.text())
        data.photo_processing_black_px = int(self.ui.lineEdit_photo_processing_black.text())
        data.photo_processing_dpi = int(self.ui.lineEdit_photo_processing_dpi.text())
        data.photo_processing_font_size_px = int(self.ui.lineEdit_photo_processing_fontsize.text())
        data.photo_processing_crop_px = int(self.ui.lineEdit_photo_processing_crop.text())

        # image counter
        list_widget = self.ui.listWidget_image_counter_exceptions
        data.image_counter_path = Path(self.ui.lineEdit_image_counter_path.text())
        data.image_counter_exceptions = [list_widget.item(i).text() for i in range(list_widget.count())]

        # image loader
        data.image_loader_path = Path(self.ui.lineEdit_image_loader_path.text())

        data.save()
        self.accept()


if __name__ == '__main__':
    import resources_rc

    app = QApplication(sys.argv)
    dlg = SendySettings()
    dlg.set_QSS()
    dlg.exec_()
    sys.exit(0)
