# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cropper/ui/help.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CropperHelp(object):
    def setupUi(self, CropperHelp):
        CropperHelp.setObjectName("CropperHelp")
        CropperHelp.resize(700, 633)
        self.label_logo = QtWidgets.QLabel(CropperHelp)
        self.label_logo.setGeometry(QtCore.QRect(230, 50, 250, 250))
        self.label_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo.setObjectName("label_logo")
        self.label_2 = QtWidgets.QLabel(CropperHelp)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 351, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(CropperHelp)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 330, 631, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)

        self.retranslateUi(CropperHelp)
        QtCore.QMetaObject.connectSlotsByName(CropperHelp)

    def retranslateUi(self, CropperHelp):
        _translate = QtCore.QCoreApplication.translate
        CropperHelp.setWindowTitle(_translate("CropperHelp", "Sendy Cropper - Help"))
        self.label_logo.setText(_translate("CropperHelp", "TextLabel"))
        self.label_2.setText(_translate("CropperHelp", "Sandy Cropper by Andrey David"))
        self.label_4.setText(_translate("CropperHelp", "[F3] - Save - Сохранить"))
        self.label_3.setText(_translate("CropperHelp", "[Ctrl+ R] - Rotate -  Повернуть"))
        self.label_6.setText(_translate("CropperHelp", "[Ctrl+ C] - Contrast - Контраст"))
        self.label_5.setText(_translate("CropperHelp", "[Ctrl+ S] - Swap - Поменять стороны"))
        self.label.setText(_translate("CropperHelp", "[Ctrl+ F] - Full screan - Полный экран"))
        self.label_7.setText(_translate("CropperHelp", "[Mouse wheel Up] - Увеличить размер рамки; [Ctrl + Mouse wheel Up] - Плавно"))
        self.label_8.setText(_translate("CropperHelp", "[Mouse wheel Down] - Уменьшить размер рамки; [Ctrl + Mouse wheel Down] - Плавно"))
