# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cropper/ui/save.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CropperSave(object):
    def setupUi(self, CropperSave):
        CropperSave.setObjectName("CropperSave")
        CropperSave.resize(550, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CropperSave.sizePolicy().hasHeightForWidth())
        CropperSave.setSizePolicy(sizePolicy)
        CropperSave.setMinimumSize(QtCore.QSize(550, 250))
        CropperSave.setMaximumSize(QtCore.QSize(550, 250))
        self.gridLayoutWidget = QtWidgets.QWidget(CropperSave)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 70, 531, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_canvas = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_canvas.setObjectName("pushButton_canvas")
        self.gridLayout.addWidget(self.pushButton_canvas, 0, 0, 1, 1)
        self.pushButton_cotton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cotton.setObjectName("pushButton_cotton")
        self.gridLayout.addWidget(self.pushButton_cotton, 1, 0, 1, 1)
        self.pushButton_banner = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_banner.setObjectName("pushButton_banner")
        self.gridLayout.addWidget(self.pushButton_banner, 0, 1, 1, 1)
        self.pushButton_matte = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_matte.setObjectName("pushButton_matte")
        self.gridLayout.addWidget(self.pushButton_matte, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(CropperSave)
        self.line.setGeometry(QtCore.QRect(10, 10, 531, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(CropperSave)
        self.line_3.setGeometry(QtCore.QRect(10, 80, 531, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.filename = QtWidgets.QLabel(CropperSave)
        self.filename.setGeometry(QtCore.QRect(20, 20, 511, 51))
        self.filename.setAlignment(QtCore.Qt.AlignCenter)
        self.filename.setObjectName("filename")

        self.retranslateUi(CropperSave)
        QtCore.QMetaObject.connectSlotsByName(CropperSave)
        CropperSave.setTabOrder(self.pushButton_canvas, self.pushButton_banner)
        CropperSave.setTabOrder(self.pushButton_banner, self.pushButton_cotton)
        CropperSave.setTabOrder(self.pushButton_cotton, self.pushButton_matte)

    def retranslateUi(self, CropperSave):
        _translate = QtCore.QCoreApplication.translate
        CropperSave.setWindowTitle(_translate("CropperSave", "Sendy Cropper - Save"))
        self.pushButton_canvas.setText(_translate("CropperSave", "[1] ХОЛСТ"))
        self.pushButton_cotton.setText(_translate("CropperSave", "[3] ХЛОПОК"))
        self.pushButton_banner.setText(_translate("CropperSave", "[2] БАННЕР"))
        self.pushButton_matte.setText(_translate("CropperSave", "[4] МАТОВЫЙ"))
        self.filename.setText(_translate("CropperSave", "В РАЗРАБОТКЕ"))
