from .settings_lex import (settings_main_btns,
                           settings_image_loader_btns,
                           image_loader_clean_folder_btns,
                           back_to_image_loader_btn,
                           settings_photo_processing_btns,
                           back_to_settings_photo_processing_btn,
                           settings_image_counter_btn,
                           settings_other_btns,
                           back_to_settings_other_btn,
                           settings_main_text,
                           settings_image_loader_text,
                           settings_photo_processing_text,
                           settings_lexicon,
                           settings_image_counter_text,
                           settings_other_text
                           )
from .lexicon import (LEXICON,
                      MAIN_BUTTONS,
                      shutdown_btns,
                      update_btn,
                      is_admin,
                      sendy_info)
