from .keyboards import (shutdown_inline_kb,
                        update_inline_kb,
                        main_kb,
                        settings_main_inline_kb,
                        settings_image_loader_inline_kb,
                        image_loader_clean_folder_inline_kb,
                        settings_photo_processing_inline_kb,
                        back_to_settings_photo_processing_inline_kb,
                        manage_photo_inline_kb,
                        back_to_image_loader_inline_kb,
                        settings_image_counter_inline_kb,
                        settings_other_inline_kb,
                        back_to_settings_other_inline_kb,
                        photo_paths
                        )
