# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sendy_cropper.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cropper(object):
    def setupUi(self, Cropper):
        Cropper.setObjectName("Cropper")
        Cropper.resize(1900, 1043)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../sendy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Cropper.setWindowIcon(icon)
        Cropper.setStyleSheet("QMainWindow {\n"
"    background-color: #EEEEEE; \n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #EEEEEE;\n"
"    color: #546E7A;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #EEEEEE;\n"
"    color: #546E7A;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #EEEEEE;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #EEEEEE;\n"
"    color: #546E7A;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #EEEEEE;\n"
"    color: black;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #EEEEEE;\n"
"    color: #546E7A;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Cropper)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(990, 0, 140, 60))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: #FAFAFA;    /* фон текстового поля */\n"
"    color: #37474F;               /* цвет текста — немного темнее, для контраста */\n"
"    border: 2px solid #546E7A;    /* рамка в твоем стиле */\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 22px;\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(1143, 0, 140, 60))
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"    background-color: #FAFAFA;    /* фон текстового поля */\n"
"    color: #37474F;               /* цвет текста — немного темнее, для контраста */\n"
"    border: 2px solid #546E7A;    /* рамка в твоем стиле */\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 22px;\n"
"}\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(1292, 0, 231, 60))
        self.textEdit_3.setStyleSheet("QTextEdit {\n"
"    background-color: #FAFAFA;    /* фон текстового поля */\n"
"    color: #37474F;               /* цвет текста — немного темнее, для контраста */\n"
"    border: 2px solid #546E7A;    /* рамка в твоем стиле */\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 22px;\n"
"}\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1743, 0, 140, 60))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 20px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 24px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(1533, 0, 200, 60))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    font: 18pt \"Helvetica\";\n"
"    color: #546E7A;\n"
"    background-color: #FAFAFA;\n"
"    border: 2px solid #546E7A;\n"
"    border-radius: 6px;\n"
"    padding: 6px 30px 6px 10px; /* отступ справа под стрелку */\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 2px solid #546E7A;\n"
"    background-color: #CFD8DC;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(390, 70, 741, 921))
        self.graphicsView.setStyleSheet("QGraphicsView {\n"
"    background-color: #FAFAFA;     /* светлый фон */\n"
"    border: 2px solid #546E7A;    /* рамка в твоих цветах */\n"
"}\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(1143, 70, 741, 921))
        self.graphicsView_2.setStyleSheet("QGraphicsView {\n"
"    background-color: #FAFAFA;     /* светлый фон */\n"
"    border: 2px solid #546E7A;    /* рамка в твоих цветах */\n"
"}\n"
"")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 371, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 1, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 1, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 1, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 2, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 4, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 2, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 4, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 6, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 6, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 6, 2, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(390, 0, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 35px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_25.setObjectName("pushButton_25")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(480, 0, 501, 61))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 20, 371, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 980, 371, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1740, 1000, 141, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 330, 371, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_27 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_2.addWidget(self.pushButton_27, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 4, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 3, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 3, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 4, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 4, 1, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_2.addWidget(self.pushButton_26, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_2.addWidget(self.pushButton_28, 5, 0, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_2.addWidget(self.pushButton_29, 5, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 310, 371, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 540, 371, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 560, 371, 421))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_33 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_3.addWidget(self.pushButton_33, 1, 0, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_3.addWidget(self.pushButton_34, 1, 1, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_3.addWidget(self.pushButton_35, 2, 0, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_3.addWidget(self.pushButton_36, 2, 1, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_3.addWidget(self.pushButton_38, 3, 0, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_3.addWidget(self.pushButton_37, 2, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_3.addWidget(self.pushButton_18, 3, 2, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_3.addWidget(self.pushButton_39, 3, 1, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_3.addWidget(self.pushButton_40, 4, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_3.addWidget(self.pushButton_30, 0, 0, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_3.addWidget(self.pushButton_32, 0, 2, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_3.addWidget(self.pushButton_31, 0, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_3.addWidget(self.pushButton_21, 5, 0, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout_3.addWidget(self.pushButton_41, 5, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_3.addWidget(self.pushButton_22, 5, 2, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_3.addWidget(self.pushButton_23, 6, 0, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_3.addWidget(self.pushButton_42, 6, 1, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout_3.addWidget(self.pushButton_43, 6, 2, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_3.addWidget(self.pushButton_44, 7, 0, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setStyleSheet("QPushButton {\n"
"    background-color: #CFD8DC;       /* светло-серый фон кнопки */\n"
"    color: #546E7A;                  /* серо-синий текст */\n"
"    border: 2px solid #546E7A;       /* цвет рамки */\n"
"    border-radius: 5px;\n"
"    padding: 12px 10px;\n"
"    font-family: \"Helvetica\";\n"
"    font-size: 16px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #B0BEC5;       /* чуть темнее при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #90A4AE;       /* ещё темнее при нажатии */\n"
"}\n"
"")
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout_3.addWidget(self.pushButton_45, 7, 1, 1, 1)
        Cropper.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Cropper)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        Cropper.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Cropper)
        self.statusbar.setObjectName("statusbar")
        Cropper.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Cropper)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Cropper)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Cropper)
        QtCore.QMetaObject.connectSlotsByName(Cropper)

    def retranslateUi(self, Cropper):
        _translate = QtCore.QCoreApplication.translate
        Cropper.setWindowTitle(_translate("Cropper", "Sendy Cropper"))
        self.textEdit.setPlaceholderText(_translate("Cropper", "ШИРИНА"))
        self.textEdit_2.setPlaceholderText(_translate("Cropper", "ВЫСОТА"))
        self.textEdit_3.setPlaceholderText(_translate("Cropper", "НОМЕР"))
        self.pushButton_2.setText(_translate("Cropper", "CROP ✂️"))
        self.comboBox.setItemText(0, _translate("Cropper", "ХОЛСТ"))
        self.comboBox.setItemText(1, _translate("Cropper", "БАННЕР"))
        self.comboBox.setItemText(2, _translate("Cropper", "ХЛОПОК"))
        self.comboBox.setItemText(3, _translate("Cropper", "МАТ ХОЛСТ"))
        self.pushButton_12.setText(_translate("Cropper", "30 × 45"))
        self.pushButton_11.setText(_translate("Cropper", "30 × 40"))
        self.pushButton_13.setText(_translate("Cropper", "30 × 55"))
        self.pushButton_15.setText(_translate("Cropper", "40 × 70"))
        self.pushButton_16.setText(_translate("Cropper", "50 × 60"))
        self.pushButton_5.setText(_translate("Cropper", "45 × 60"))
        self.pushButton_17.setText(_translate("Cropper", "50 × 70"))
        self.pushButton_19.setText(_translate("Cropper", "60 × 80"))
        self.pushButton_20.setText(_translate("Cropper", "60 × 90"))
        self.pushButton_14.setText(_translate("Cropper", "40 × 60"))
        self.pushButton.setText(_translate("Cropper", "20 × 30"))
        self.pushButton_24.setText(_translate("Cropper", "90 × 120"))
        self.pushButton_25.setText(_translate("Cropper", "⭮"))
        self.label_2.setText(_translate("Cropper", "MADE BY DAVID_AG"))
        self.pushButton_27.setText(_translate("Cropper", "35 × 35"))
        self.pushButton_8.setText(_translate("Cropper", "70 × 70"))
        self.pushButton_6.setText(_translate("Cropper", "50 × 50"))
        self.pushButton_7.setText(_translate("Cropper", "60 × 60"))
        self.pushButton_10.setText(_translate("Cropper", "90 × 90"))
        self.pushButton_9.setText(_translate("Cropper", "80 × 80"))
        self.pushButton_26.setText(_translate("Cropper", "20 × 20"))
        self.pushButton_4.setText(_translate("Cropper", "30 × 30"))
        self.pushButton_3.setText(_translate("Cropper", "40 × 40"))
        self.pushButton_28.setText(_translate("Cropper", "100 × 100"))
        self.pushButton_29.setText(_translate("Cropper", "110 × 110"))
        self.pushButton_33.setText(_translate("Cropper", "30 × 50"))
        self.pushButton_34.setText(_translate("Cropper", "30 × 60"))
        self.pushButton_35.setText(_translate("Cropper", "40 × 50"))
        self.pushButton_36.setText(_translate("Cropper", "40 × 80"))
        self.pushButton_38.setText(_translate("Cropper", "50 × 55"))
        self.pushButton_37.setText(_translate("Cropper", "40 × 90"))
        self.pushButton_18.setText(_translate("Cropper", "50 × 80"))
        self.pushButton_39.setText(_translate("Cropper", "50 × 75"))
        self.pushButton_40.setText(_translate("Cropper", "50 × 90"))
        self.pushButton_30.setText(_translate("Cropper", "20 × 35"))
        self.pushButton_32.setText(_translate("Cropper", "25 × 30"))
        self.pushButton_31.setText(_translate("Cropper", "20 × 40"))
        self.pushButton_21.setText(_translate("Cropper", "70 × 80"))
        self.pushButton_41.setText(_translate("Cropper", "70 × 90"))
        self.pushButton_22.setText(_translate("Cropper", "70 × 120"))
        self.pushButton_23.setText(_translate("Cropper", "80 × 110"))
        self.pushButton_42.setText(_translate("Cropper", "80 × 120"))
        self.pushButton_43.setText(_translate("Cropper", "80 × 130"))
        self.pushButton_44.setText(_translate("Cropper", "90 × 110"))
        self.pushButton_45.setText(_translate("Cropper", "90 × 130"))
        self.menu.setTitle(_translate("Cropper", "Файл"))
        self.menu_2.setTitle(_translate("Cropper", "Помощь"))
        self.action.setText(_translate("Cropper", "Открыть"))
        self.action_2.setText(_translate("Cropper", "О программе"))
